### ISSUE TITLE
14 Create and explore a semantic model

### ISSUE THREAD

**Issue by nugysemail** [MicrosoftLearning/mslearn-fabric#113]
# Module: 14 Create and explore a semantic model
#### Step: 5

Description of issue
Can not create New Semantic Model, with this error message :
"We couldn't create the see through model".

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/2998731/634c2002-57e0-4841-9bd2-d23cb7701c94)

**Comment by afelix-95** [comment]
This seems like a temporary connectivity issue. The semantic model name accepts special characters and every other parameter is bound to valid options, leaving no room for invalid user input. So, there shouldn't be any invalid parameters when creating the model. If the problem persists, please re-open the issue, otherwise I think we can consider it closed for now. Same as #110
