### ISSUE TITLE
Workspace creation failures

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/mslearn-fabric#178]
We are getting intermittent yet frequent failures to create workspaces. This naturally blocks lab progress. Sometimes the workspaces creation completes after many minutes, usually it seems to be stuck indefinitely.

The symptom is a spinning circle:

![image](https://github.com/user-attachments/assets/a95cc8c5-03b4-4510-b7ae-1e02019d6356)

We raised it to Skillable under ticket 2410788, in case it's environmental and specific to that ALH's tenants. It may also be a platform glitch in Fabric itself.

Has anyone else experienced the same issue in Skillable, other ALHs, or in local environments? If so, have you been able to find a workaround?

_Note: We've tried manually rerunning the workspace creation in case the 1st attempt fails. This only appears to work sometimes. Often the 2nd attempt also gets "stuck"._

**Comment by VitalyMCT** [comment]
@afelix-95 I understand you are helping with issue resolution in this repo. Thanks again for your help!

Can you please confirm you can repro this one?

**Comment by afelix-95** [comment]
@VitalyMCT I've been testing the labs in this repo throughout the week, both in VM environment and locally, and only had this issue one time in VM env. Simply refreshing the page and trying to create the workspace again was enough to solve it. 

That is most likely a temporary Fabric backend stability problem that can happen when you have too many users trying to create new resources in the same region at the same time. Since you already submitted a ticket to Skillable support, if the issue persists, I recommend also submitting feedback in the Fabric portal.

I'll close this issue now since it is not directly related to the repo content, but feel free to open it again if it continues to happen over time.

**Comment by VitalyMCT** [comment]
Thanks @afelix-95. It happens extremely frequently in Skillable now. I would estimate it happens 50%-70% of the times a lab is launched. And it's been happening for at least 1 week, perhaps more. So not an isolated issue at all.

Refreshing the page does not always solve the issue either. I sometimes have to try 3, 4 or 5 times, with waits in between, before the workspace is finally created. It's very frustrating. 

Yes, it may be a platform issue exacerbated by something within the tenant - ex. the specific region's capacity, # of workspaces, proportion of workspaces running trial vs paid, etc.

**Can you please re-open the issue so we can gather feedback from the other MCTs?** This will also help everyone understand if it's limited to just Skillable or if other ALHs are impacted. Only Microsoft personnel can close & open issues in this repo.

**Comment by VitalyMCT** [comment]
@AngieRudduck Skillable ticket already opened by me. See note in original report. Perhaps you can influence its faster resolution within Skillable. Thanks.

**Comment by AngieRudduck** [comment]
@VitalyMCT I appreciate the creative solution. If we can't work through the issue with the tenant, then we can explore this more. Even for labs, we don't want to teach My Workspace - start with good habits first. There's also some oddness creating Fabric items on a trial in My Workspace that might present different issues.

**Comment by SkillableKA** [comment]
For awareness, we are aware of the workspace creation delay and are working with Microsoft on a resolution to the issue.
