### ISSUE TITLE
mslearn-fabric/Instructions/Labs 03-delta-lake

### ISSUE THREAD

**Issue by jstatic29** [MicrosoftLearning/mslearn-fabric#33]
# Module: 00
#### Step: 4

Description of issue

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/20371891/dbf5de85-d397-48eb-a53f-8e88cd9a5a00)

Need a forward slash concatenated before txt filename so that the file goes into Files/streaming.

Current behavior the file has the inputPath variable prepended to filename which goes into Files.

Repro steps:

1. Run step 1 and Step 4
1. Look at root Files
1. See txt files in root Files.

**Comment by shannonlindsay** [comment]
Thanks for your feedback James - we'll take a look.

**Comment by Mihai-Ac** [comment]
Hello @jstatic29 

The inputPath variable is set to inputPath = 'Files/data/', meaning that the streaiming content is saved in the **data** folder, under *Files*(and not dirrectly under *Files*).
 When running this command in the lab, a new folder with that name will be created, where the *data.txt* file will be saved.
![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/110993710/69bfecff-a1fc-470f-a382-de160c8ebd8d)
The code is correct, and , as seen in the screenshot above, it creates the **data** folder and the *data.txt* file.

As for the suggestion to add a forward slash before the txt filename, this will result in having a double forward slash **Files/data//data.txt** , because the inputPath already contains one after the folder name.
