### ISSUE TITLE
Lab 5 has outdated instructions and screenshots

### ISSUE THREAD

**Issue by KoenVerbeeck** [MicrosoftLearning/mslearn-fabric#44]
# Module:  Ingest Data with Dataflows Gen2 in Microsoft Fabric 
#### Step: 1 & 2

It says monthno and OrderDate cannot be saved because of the data types. However, orderdate is already a date/time (probably derived implicitly when the custom column was created), so there's no issue with it.
In step 2, it tells you to cancel and go set the data types. However, the data type is now included in the screen, so there's no need to cancel, you can do it directly when creating the destination.

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/7213731/2da410ee-3f38-4fb8-b9fa-b2b30ba0f6cd)

**Comment by AngieRudduck** [comment]
@KoenVerbeeck when you created the column, did you explicitly set the data type? 

I'm not able to reproduce your experience. When I create a new custom column only using the code, and *not* adjusting the data type, it defaults to ANY, which is what's being identified here.

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/34583336/0fd05eba-56eb-49fc-abfd-569fd2d40b0a)


![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/34583336/edfbfab6-c3b6-4e49-8b8e-4036ebb6b78b)

**Comment by KoenVerbeeck** [comment]
@AngieRudduck that's my point exactly :) In your screenshot you can see there's a source type column. In the lab itself, it's not there and the instructions tell you to cancel and manually set the data type. But, as you can see, this is not necessary as you can modify the data type directly in the column mapping.

**Comment by AngieRudduck** [comment]
Hi @KoenVerbeeck, I understand what your point is. From my point, we are going to have a diverse audience learning this concept, so since the behavior isn't required in the column creation, the intent here was to teach users to make sure to set the data type before completing the ingestion. However, now that you can change the data type on this page, we may need to revise it to be "review data types are valid" instead of cancel and redo. Hooray for product improvements. :)

**Comment by AngieRudduck** [comment]
@KoenVerbeeck @Mihai-Ac We've updated the instructions, thanks for the feedback!
