### ISSUE TITLE
Lab 4: Pipeline containing notebook fails with error 2010

### ISSUE THREAD

**Issue by Matlock1000D** [MicrosoftLearning/mslearn-fabric#48]
# Module: 00
#### Step: 07

While trying to run the pipeline containing a notebook, I get an error on the notebook activity saying "2010 User configuration issue. Hit unexpected exception, please retry.” Tried retrying and refreshing browser page. Tried removing the parameter specified in step 6, same error. I select the notebook from a drop-down list so not much else I can edit. The notebook runs fine when run from the notebook editor.
![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/55192621/1d129fa5-e91f-4cc1-9f72-fb5616033a35)

Repro steps:

1. Follow lab tutorial until Modify the pipeline step 7

**Comment by Mihai-Ac** [comment]
Hello @Matlock1000D 

Thanks for reporting this issue. We´ll look into it and let you know when we have a fix.

**Comment by marynakrylova** [comment]
I have experienced the very same issue today. Notebook runs without any errors when executed in Notebook editor and fails each time when I try to run a pipeline. 
I got some additional information by clicking on the output symbol of the failed activity (see screenshot). It says something about invalid LakehouseWorkspaceId... Can it be due to the fact that all my fabric ressources are created inside "My Workspace"? I do not have the rights to create additional workspaces so I am forced to complete all lab sessions inside my own personal workspace.

![image](https://github.com/MicrosoftLearning/mslearn-fabric/assets/138792183/0c5a9720-3940-468f-88a3-a299ec582b76)

**Comment by Matlock1000D** [comment]
In my case I have a dedicated workspace, but still get the error. I tried again just now, but the problem persist. Thank you @marynakrylova for pointing out the way to get a more detailed error message. I checked and seem to be getting the same one, though I don't know what could be done.

**Comment by nrsharp1** [comment]
I am also experiencing this issue while working through the pipleline tutorial.  The notebook runs successfully on it's own, but not when run in a pipeline.  LakehouseWorkspaceId is not populated in the input JSON.

**Comment by MarkFromTheInternet** [comment]
Got the same "error 2010" when running this today. Details from the error message:
"Spark SQL queries are only possible in the context of a lakehouse. Please attach a lakehouse to proceed"

In my case, I had to re-open the Lakehouse item. I briefly saw a message in the upper right that it was either reconnecting or reopening a session to the LH. After that, the pipeline ran fine.

In the Input JSON for that activity, there's not any reference to LakehouseWorkspaceId, but there is a workspaceId value.

**Comment by Mihai-Ac** [comment]
Hello  @Matlock1000D 
Are you still seeing this issue?
I have tried to reproduce it now and it seems to be fixed.

**Comment by Matlock1000D** [comment]
Thanks for following up! I don't have access to that Fabric environment anymore, but good to know that it's been addressed.
